[package]
name = "data_assets"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
dotenv = "0.15.0"
ic-cdk = "0.7.4"
ic-cdk-macros = "0.6.0"
itertools = "0.10.5"
serde = "1.0.160"