[package]
name = "data_assets"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "data_assets"
path = "src/main.rs"

# [lib]
# crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.7.4"
ic-cdk-macros = "0.6.0"
itertools = "0.10.5"
serde = "1.0.160"